### PR TITLE
moved displayFile in asyncThread #16

### PR DESCRIPTION
**Pull request by Swati4star**
Fix for https://github.com/polypmer/fissure-android/issues/16

### CODE REVIEW

**Review by fenimore — APPROVED** [review]
Looks great!

**Comment by fenimore** [comment]
Hey @Swati4star thanks again for the pull request, looks great, but your branch is behind the master; I'm told I need you to rebase and push back to the branch before I can merge.

Super looking btw :D

**Comment by fenimore** [comment]
I'm a bit confused how to proceed honestly (I'm kinda new to this), but I found this article that might be useful:
https://help.github.com/articles/about-pull-request-merges/#rebase-and-merge-your-pull-request-commits

**Comment by Swati4star** [comment]
@polypmer  I have created new PR https://github.com/polypmer/fissure-android/pull/19. :)

**Pull request closed without merging**
